spring:
  profiles:
    active: native
  cloud:
    config:
      uri: http://localhost:8888
      name: application-zuul
      profile: dev
#        label:
#配置服务器的默认端口是 8888， 如果修改了默认端口，
#  则客户端项目中就不能在application.yml或application.properties中配置spring.cloud.config.uri，
#  必须在bootstrap.yml或是bootstrap.properties中配置，原因是bootstrap开头的配置文件会优先加载和配置。
#spring.cloud.config.uri: 配置服务中心的网址
#spring.cloud.config.name: 配置文件的前缀名
#spring.cloud.config.label: 配置仓库的分支。如果是本地读取，可不配置
#spring.cloud.config.profile: 配置文件的环境标识
#dev: 开发环境
#test: 测试环境
#prod: 生产环境


